# Generated by Django 5.0.7 on 2024-07-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_tr',
        ),
    ]
